#!/usr/bin/env python
"""Prepare a NICE-SLAM-layout Replica scene for ORB-SLAM3 RGB-D.

Why this exists
---------------
Replica's Demo layout stores color (1296x968, K_color) and depth (640x480,
K_depth) from *two virtual cameras that share optical centre and orientation*
(the extrinsic files are identity), so the two streams are NOT pixel-registered
but differ only by intrinsics/resolution. ORB-SLAM3 RGB-D needs depth
registered to the RGB grid, so we resample each depth frame onto the colour
grid with a fixed, intrinsic-derived map (cv2.remap, INTER_NEAREST, keeps the
uint16-mm values exact).

Outputs (into --out, the ORB "sequence" dir)
--------------------------------------------
    rgb/<i:06d>.jpg      symlink to the original colour frame (BGR)
    depth/<i:06d>.png    registered depth, uint16 millimetres, colour resolution
    assoc.txt            `ts rgb/<..> ts depth/<..>` in increasing ts (i*ts_step)
    orb.yaml             ORB-SLAM3 RGB-D config (colour K, factor 1000 mm->m)

The feed order is the natural order of the colour files, so feed index i maps
1:1 onto raw frame id i for the 0..N-1 Demo layout.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root
from scripts.orb_slam.common import load_k, natural_key

# Colour camera params in a Replica Demo frame, for the header comment
IMG_EXT = {".jpg", ".jpeg", ".png"}


def _yaml_text(W, H, fx, fy, cx, cy, n_features=2000, fps=30):
    # Schema mirrors Examples/RGB-D/TUM1.yaml of ORB-SLAM3 master (verified).
    # Camera.RGB = 0 because cv::imread yields BGR images -> ORB does BGR2GRAY.
    return f"""%YAML:1.0

# Auto-generated by replica_prep_orb.py for Replica Demo colour camera
File.version: "1.0"

Camera.type: "PinHole"

Camera1.fx: {fx:.6f}
Camera1.fy: {fy:.6f}
Camera1.cx: {cx:.6f}
Camera1.cy: {cy:.6f}

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

Camera.width: {W}
Camera.height: {H}

Camera.fps: {fps:d}

# 0: BGR, 1: RGB  (cv::imread returns BGR)
Camera.RGB: 0

Stereo.ThDepth: 40.0
Stereo.b: 0.0745

# uint16 depth in millimetres -> metres
RGBD.DepthMapFactor: 1000.0

ORBextractor.nFeatures: {n_features}
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--scene", type=Path, required=True, help="raw Replica scene (NICE-SLAM layout)")
    ap.add_argument("--out", type=Path, required=True, help="ORB sequence dir to create")
    ap.add_argument("--color-dir", default="frames/color")
    ap.add_argument("--depth-dir", default="frames/depth")
    ap.add_argument("--intrinsics-dir", default="frames/intrinsic")
    ap.add_argument("--ts-step", type=float, default=0.02, help="seconds between fed frames")
    ap.add_argument("--max-frames", type=int, default=0, help="limit feed to first N frames (0 = all)")
    ap.add_argument("--probe", action="store_true", help="print plan, write nothing")
    args = ap.parse_args()

    scene = args.scene
    color_dir = scene / args.color_dir
    depth_dir = scene / args.depth_dir
    int_dir = scene / args.intrinsics_dir

    colors = sorted((f for f in color_dir.iterdir() if f.suffix.lower() in IMG_EXT), key=natural_key)
    if not colors:
        raise SystemExit(f"no colour images under {color_dir}")
    fx_c, fy_c, cx_c, cy_c = load_k(int_dir / "intrinsic_color.txt")
    fx_d, fy_d, cx_d, cy_d = load_k(int_dir / "intrinsic_depth.txt")

    first = cv2.imread(str(colors[0]))
    H, W = first.shape[:2]
    if args.max_frames:
        colors = colors[: args.max_frames]
    n = len(colors)

    print(f"colour frames : {n}   first={colors[0].name}  last={colors[-1].name}")
    print(f"colour size   : {W}x{H}   K_c fx={fx_c:.3f} fy={fy_c:.3f} cx={cx_c:.3f} cy={cy_c:.3f}")
    print(f"depth   size  : 640x480   K_d fx={fx_d:.3f} fy={fy_d:.3f} cx={cx_d:.3f} cy={cy_d:.3f}")
    print(f"ts step       : {args.ts_step}s   out={args.out}")
    if args.probe:
        return

    (args.out / "rgb").mkdir(parents=True, exist_ok=True)
    (args.out / "depth").mkdir(parents=True, exist_ok=True)

    # remap maps: colour pixel (y,x) samples depth pixel given by the shared
    # centre/projection. x' = fx_d*(x-cx_c)/fx_c + cx_d, y' likewise with fy.
    yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
    map_x = (xx - cx_c) * (fx_d / fx_c) + cx_d
    map_y = (yy - cy_c) * (fy_d / fy_c) + cy_d

    assoc = []
    for i, c in enumerate(colors):
        stem = f"{i:06d}"
        rgb_dst = args.out / "rgb" / (stem + c.suffix.lower())
        if not rgb_dst.exists():
            os.symlink(c.resolve(), rgb_dst)

        d = cv2.imread(str(depth_dir / (c.stem + ".png")), cv2.IMREAD_UNCHANGED)
        if d is None:
            raise SystemExit(f"missing depth for {c.name}")
        reg = cv2.remap(d, map_x, map_y, interpolation=cv2.INTER_NEAREST)
        cv2.imwrite(str(args.out / "depth" / (stem + ".png")), reg)
        ts = i * args.ts_step
        assoc.append(f"{ts:.6f} rgb/{stem}{c.suffix.lower()} {ts:.6f} depth/{stem}.png")

    (args.out / "assoc.txt").write_text("\n".join(assoc) + "\n")
    (args.out / "orb.yaml").write_text(_yaml_text(W, H, fx_c, fy_c, cx_c, cy_c))
    print(f"wrote {n} rgb symlinks + {n} registered depth PNGs -> {args.out}")
    print(f"wrote assoc.txt (first line):\n  {assoc[0]}")
    print(f"wrote orb.yaml (colour K, factor 1000)")


if __name__ == "__main__":
    main()
